call RunScript('plugin-confs/airline.vim')
call RunScript('plugin-confs/fzf.vim')
call RunScript('plugin-confs/nerdtree.vim')
call RunScript('plugin-confs/ale.vim')
call RunScript('plugin-confs/lsp.vim')
